# -*- coding: utf-8 -*-
"""LR_8_task_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RCYDSihlaBK0wyTnzHv-TRZkw96gaMLh
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np


# Завантаження та відображення захопленого зображення
img = cv2.imread("Ishchuk.jpg")
cv2_imshow(img)
cv2.waitKey(0)

# Ініціалізація класифікатора для виявлення обличчя
faceCascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

# Перетворення зображення у відтінки сірого
imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Виявлення обличчя на зображенні
faces = faceCascade.detectMultiScale(imgGray, 1.1, 4)

# Обробка та виділення областей, де знайдено обличчя
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

# Виведення зображення з виділеними областями обличчя
cv2_imshow(img)

# Очікування натискання клавіші для завершення відображення
cv2.waitKey(0)