# -*- coding: utf-8 -*-
"""lr_5_task_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qmSEcAH3Gigf_ORz8dm-2l0gqeGD6QZO
"""

!pip install neurolab

import numpy as np
import matplotlib.pyplot as plt
import neurolab as nl

# Генерація тренувальних даних
min_val = -15
max_val = 15
num_points = 130
x = np.linspace(min_val, max_val, num_points)
y = 2 * np.square(x) + 9
y /= np.linalg.norm(y)

# Створення даних та міток
data = x.reshape(num_points, 1)
labels = y.reshape(num_points, 1)

# Побудова графіка вхідних даних
plt.figure()
plt.scatter(data, labels)
plt.xlabel('Параметр 1')
plt.ylabel('Параметр 2')
plt.title('Вхідні дані')
plt.show()

# Визначення багатошарової нейронної мережі з трьома прихованими
# шарами. Перший прихований шар складається із двох нейронів,
# другий прихований шар містить два нейрони, а третій шар - один нейрон.
nn = nl.net.newff([[min_val, max_val]], [2, 2, 1])

# Завдання методу оптимізації Adam
nn.trainf = nl.train.train_gdm

# Тренування нейронної мережі
error_progress = nn.train(data, labels, epochs=5000, show=500, lr=0.01, goal=0.01)

# Виконання нейронної мережі на тренувальних даних
y_pred = nn.sim(data).reshape(num_points)

# Побудова графіка помилки навчання
plt.figure()
plt.plot(error_progress)
plt.xlabel("К-ть епох")
plt.ylabel("Помилка навчання")
plt.title('Зміна помилки навчання')

# Побудова графіка результатів
x_dense = np.linspace(min_val, max_val, num_points * 2)
y_dense_pred = nn.sim(x_dense.reshape(x_dense.size, 1)).reshape(x_dense.size)
plt.figure()
plt.plot(x_dense, y_dense_pred, '-', x, y, '.', x, y_pred, 'p')
plt.title('Апроксимація функції за допомогою багатошарової нейронної мережі')
plt.show()