# -*- coding: utf-8 -*-
"""lr_3_task_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Itl9lsX7Vk9xKRWHwMEL255psgI9_z5I
"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pickle
import numpy as np
from sklearn import linear_model
import sklearn.metrics as sm
import matplotlib.pyplot as plt
from google.colab import files

# Завантаження даних з файлу
file_path = 'data_regr_5.txt'  # Вкажіть правильний шлях до вашого файлу
data = np.loadtxt(file_path, delimiter=',')
# Розділення даних на вхідну змінну (X) та відгук (y)
X = data[:, 0]  # Вкажіть правильний індекс стовпця для вашої змінної
y = data[:, 1]  # Вкажіть правильний індекс стовпця для відгуку
# Розділення даних на навчальний та тестовий набори
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Створення та навчання моделі
regressor = LinearRegression()
regressor.fit(X_train.reshape(-1, 1), y_train)

# Прогнозування на тестовому наборі
y_pred = regressor.predict(X_test.reshape(-1, 1))

# Відображення результуючої регресійної моделі
plt.scatter(X_test, y_test, color='blue')
plt.plot(X_test, y_pred, color='red', linewidth=3)
plt.xlabel('Вхідна змінна')
plt.ylabel('Відгук')
plt.show()
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, median_absolute_error, explained_variance_score, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Середньоквадратична похибка (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
medae = median_absolute_error(y_test, y_pred)
evs = explained_variance_score(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Linear regressor performance:")
print(f"Mean absolute error: {mae:.2f}")
print(f"Mean squared error: {mse:.2f}")
print(f"Median absolute error: {medae:.2f}")
print(f"Explain variance score: {evs:.2f}")
print(f"R2 score: {r2:.2f}")

# Оцінка нового передбачення з використанням навченої моделі
y_test_pred_new = regressor.predict(X_test.reshape(-1, 1))
new_mae = mean_absolute_error(y_test, y_test_pred_new)

print(f"\nNew mean absolute error: {new_mae:.2f}")